# Generated by Django 5.1.1 on 2024-10-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('address', models.CharField()),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField()),
            ],
        ),
    ]
