# Generated by Django 5.1.1 on 2024-10-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profie_pics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profie_pics',
            new_name='Profie_pictures',
        ),
    ]
