# Generated by Django 5.1.1 on 2024-10-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_profie_pics_profie_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profie_pictures',
            name='profile_pic',
            field=models.ImageField(upload_to='profle_pics/'),
        ),
    ]
