# Generated by Django 5.1.1 on 2024-10-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profie_pictures_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Profie_pictures',
        ),
    ]
