# Generated by Django 5.1.1 on 2024-10-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
