# Generated by Django 5.1.1 on 2024-10-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_cart_grant_total_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='grant_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
