# Generated by Django 5.1.1 on 2024-10-15 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_delivery_details_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_details',
            old_name='payment_id',
            new_name='address',
        ),
        migrations.AddField(
            model_name='delivery_details',
            name='delivery_token',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_details',
            name='user_token',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.cart'),
        ),
    ]
