# Generated by Django 5.1.1 on 2024-10-15 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_rename_payment_id_delivery_details_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_details',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.cart'),
        ),
    ]
