# Generated by Django 5.1.1 on 2024-10-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_delivery_details_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_details',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
