# Generated by Django 5.1.1 on 2024-10-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_delivery_details_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
